[package]
name = "cli-commentator-desktop"
version = "0.2.2"
edition = "2021"

[lib]
name = "cli_commentator_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
process-wrap = { version = "10", features = ["std", "process-group", "job-object"] }
tauri-plugin-autostart = "2"
tauri-plugin-updater = "2"
