export type {
  CommentaryMeta,
  CommentaryPayload,
  CommentarySpeech,
  CommentarySpeechDisposition,
  CommentarySpeechReason,
  CreateProfileInput,
  DetectedSource,
  Event,
  EventPriority,
  EventType,
  InputMode,
  LaunchSessionInput,
  Profile,
  ProfileLLMProviders,
  ProfileSummary,
  ProviderName,
  PtySize,
  SourceMode,
  SourceState,
  Style,
  UpdateProfileInput,
  WsIncoming,
  WsOutgoing,
} from "@cli-commentator/shared";

export type CommentaryDisplayMode = "narration" | "explanation" | "both";
